services:
  bloglist-frontend:
    image: bloglist-frontend
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api
    
  bloglist-backend:
    image: bloglist-backend
    build:
        context: ./backend
        dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    env_file:
      - ./backend/.env

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: bloglist-reverse-proxy
    depends_on:
      - bloglist-frontend
      - bloglist-backend